import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Geist, Geist_Mono, Playwrite_IN } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playwriteIndia = Playwrite_IN({
  variable: "--font-playwrite-india",
  weight: ["100", "200", "300", "400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playwriteIndia.variable} antialiased h-screen bg-secondaryBgImage bg-no-repeat bg-center bg-cover overflow-hidden`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
