import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Playwrite_IN, Mulish } from "next/font/google";

const playwriteIndia = Playwrite_IN({
  variable: "--font-playwrite-india",
  weight: ["100", "200", "300", "400"],
});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin", "vietnamese"],
  style: ["normal", "italic"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playwriteIndia.variable} ${mulish.className} antialiased h-screen bg-secondaryBgImage bg-no-repeat bg-center bg-cover overflow-hidden`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
